const projects={
  morse:{code:'M/36 — COMPACT MACHINE INTENT',status:'EXPERIMENTAL / PRE-v0.1',title:'How little does one machine need to say for another machine to act correctly?',description:'A compact language for machine intent—less chatter, less ambiguity and faster action between systems that already understand each other.',story:'It began with agents repeatedly sending verbose instructions to systems that already shared context. If both machines know the vocabulary, why keep retransmitting the sentence? That question became Compact Machine Intent: M36 for a constrained frame and M366 when more context is genuinely required.',question:'Benchmark semantic fidelity, payload size, latency, failure behaviour and parser complexity against appropriate alternatives. The goal is not to manufacture a win. It is to discover where compact intent is actually useful.',link:'https://thegrahamfoundation.github.io/Morse-36/workbench/',label:'Open Morse/36 Workbench'},
  phantom:{code:'PHANTOM.JS — INTEGRATION UTILITY LAYER',status:'PUBLIC · v0.1.9-BETA',title:'What if integration scripting had a small, predictable standard library?',description:'The integration engineer’s standard library—104+ tested utilities replacing brittle scripts with fast, predictable building blocks.',story:'Integration engines make simple transformations surprisingly repetitive. Phantom grew from that friction: the same map access, parsing, formatting and defensive checks being rewritten inside channel after channel. The experiment is deliberately practical: remove boilerplate without hiding the engine underneath.',question:'Keep the surface predictable and portable across supported integration engines, with explicit errors and reproducible tests. The current public record reports 104 functions and 284 test cases.',link:'https://github.com/TheGrahamFoundation/phantom',label:'Inspect Phantom'},
  chalk:{code:'CHALK — MATHEMATICAL VISUAL LANGUAGE',status:'INTERNAL RESEARCH',title:'Can an AI describe a mathematical drawing without drawing pixels?',description:'A visual reasoning layer for AI—turning mathematical intent into precise, interactive geometry instead of disposable images.',story:'Chalk came from Sophia. A tutor can explain a circle, angle or function in words, but teaching becomes different when the explanation can become an inspectable object on a canvas. The useful abstraction was not image generation. It was a vocabulary for mathematical intent: point, segment, circle, polygon, angle, function graph, arc and label.',question:'Test whether a constrained visual specification produces reliable, editable mathematical diagrams across varied tutoring prompts while keeping the renderer replaceable. The repository remains internal, so implementation details are not publicly linked.',link:'https://github.com/TheGrahamFoundation',label:'Foundation record'},
  helix:{code:'HELIX — REPOSITORY NARRATIVE',status:'INTERNAL RESEARCH',title:'Every repository has a story. Can its history be read like one?',description:'The living memory of software—transforming commits, releases and deployments into the story of how a system became what it is.',story:'It started while building Blend. The repository knew exactly how the product had evolved, but its history was difficult to communicate to anyone who was not already living inside the codebase. Helix asks git for the narrative layer: where work branched, who carried it, what merged, and when that change reached a checkpoint.',question:'Build a read-only model that can turn local, GitHub or GitLab history into useful interactive and static views without writing back to the repository. The current roadmap includes parsing, Mermaid export, SVG rendering, author lanes and CI/CD overlays.',link:'https://github.com/TheGrahamFoundation',label:'Foundation record'}
};
const panel={code:document.querySelector('#project-code'),status:document.querySelector('#project-status'),title:document.querySelector('#project-title'),description:document.querySelector('#project-description'),story:document.querySelector('#project-story'),question:document.querySelector('#project-question'),link:document.querySelector('#project-link')};
function selectProject(key){const p=projects[key];if(!p)return;panel.code.textContent=p.code;panel.status.textContent=p.status;panel.title.textContent=p.title;panel.description.textContent=p.description;panel.story.textContent=p.story;panel.question.textContent=p.question;panel.link.href=p.link;panel.link.innerHTML=`${p.label} <span>↗</span>`;document.querySelectorAll('[data-project]').forEach(el=>{const selected=el.dataset.project===key;el.classList.toggle('active',selected);if(el.matches('[role="tab"]'))el.setAttribute('aria-selected',selected)});document.querySelector('#research')?.scrollIntoView({behavior:'smooth',block:'start'});}
document.querySelectorAll('[data-project]').forEach(el=>el.addEventListener('click',()=>selectProject(el.dataset.project)));
selectProject('morse');